'use strict';
/**
 * @fileoverview simplicity/view_controllers/input_page_view_controller.js
 * 
 * InputPageViewController
 * 
 * This class serves as the base class for all form interaction view controllers,
 * such as the SignupViewController.
 * 
 * It constructs views using the following components:
 * 
 *  - TextField: text input from textfield.js
 *  - DropdownButton: select with table from dropdown_button.js
 *  - RadioButton: select with radio buttons from radio_button.js *todo
 *  - Title: title of the form field or page
 *  - Description: description of the form field or page
 *  - FieldTitle: title of a specific field *todo
 *  - FieldDescription: description of a specific field *todo
 *  - AlertText: alert or error message text
 *  - NextButton: button for navigating to the next page
 *  - BackButton: button for navigating to the previous page
 * 
 * Subclasses of InputPageViewController primarily focus on the validation of each form value.
 * 
 * This class provides the following common functionalities:
 *  1. Values are retained in the cookie during each page transition.
 *  2. The URL is rewritten using JavaScript for each screen transition.
 *  3. Values are not lost when the browser reloads or navigates back.
 * 
 * Usage example:
 *
 * <code>
 * // Define a data model to be submitted.
 * class User {
 *     constructor(first_name, last_name, country) {
 *         this.first_name = first_name;
 *         this.last_name = last_name;
 *         this.country = country;
 *     }
 * }
 * 
 * // Define SignupViewController extending from InputPageViewController
 * class SignupViewController extends InputPageViewController {
 *     constructor(_id, pages, dataModelClass) {
 *         super(_id, pages, dataModelClass)
 *     }
 * }
 * 
 * // Initialize the validators
 * let requiredValidator = new Validator(titleField, ValidationErrorType.required, 'This field is required');
 * let lengthValidator = new Validator(titleField, ValidationErrorType.length, 'The length of the text exceeds the limit', [140]);  // assuming max length of 140
 * 
 * let validators = [requiredValidator, lengthValidator];
 * 
 * // Initialize the TextField
 * let titleField = new TextField(
 *     'parentView',  // parent_id
 *     'titleField',  // id
 *     TextFieldType.multiplelines,  // single or multi
 *     'title(reqired)',  // title
 *     'title',  // field name
 *     'Mona Lisa Title and subject',  // placeholder
 *     'div',  // the HTML tag
 *     validators,  // Pass in the validators
 *     140,  // max text count
 *     4,  // init rows
 *     false,  // vertical flex
 *     true,  // assuming the title is visible
 *     false  // assuming password mode is off
 * );
 * 
 * // Create pages
 * let page_1 = new Page([titleField]);  // Add other components as needed
 * let page_2 = new Page([]);  // Add components as needed
 * let pages = [page_1, page_2];
 * 
 * // Initialize a SignupViewController
 * let vc = new SignupViewController(
 *     'SignupView',
 *     pages,
 *     User,  // User model class
 *     new LoadingBar('content', 'loading')
 * );
 * 
 * // After the initialization, the DOM elements are dynamically generated by InputPageViewController
 * 
 * </code>
 * 
 * @author kaz@thinkxinc.com (Kazuki Otsuka)
 **/

/**
 * InputPageViewController DataModel class.
 * 
 * @param {dict} defaults default key:value of fields retrieved from _restoreValuesFromCookie()
 * @constructor 
 */
class InputPageViewDataModel {
    // TODO:
    //  inherit constructor in child class by 
    //  super(defaults);
    // 
    // NOTE:
    //  Object.assign(this, defaults);
    //  doesn't refer to the child object.

    //constructor(defaults = {}) {
    //    Object.assign(this, defaults);
    //}
 
    /**
     * Convert object to json.
     * @returns {json} convert to json string
     */
    json() {
        return JSON.stringify(this);
    }
}

/**
 * InputPageViewController - This class is responsible for managing the user interactions on the input page, 
 * ensuring protocol adherence of its various components, and managing the state of the page.
 *
 * @param {string} parent_id - The id of the parent element where this controller's view will be appended.
 * @param {string} id - The id for this page view controller instance.
 * @param {Array} pages - An array containing the components to be displayed on each page. Each element of the array should be an array of components.
 * @param {Object} dataModelClass - The class of the data model that this controller will use to store its state.
 * @param {Object} locale - The localization data used for this view controller.
 * @param {string} lang - The language code to be used in the localization process.
 * @param {Object} loading - The object that manages the loading state of the view.
 *
 * This class also includes various getters and setters for managing the state of the controller 
 * (e.g. current page, errors, values etc.). Moreover, it has methods for checking the protocol adherence of
 * the components, setting elements, setting event handlers, managing component values, setting alerts, 
 * validation, network requests, loading states, navigation, and others.
 *
 * Some methods must be overridden in a subclass, namely:
 * - viewLoaded()
 * - pageChanged(page)
 * - valueChanged(component, value)
 * - unfocused(component, value)
 * - backButtonTapped(backButton)
 *
 * This controller expects its components to adhere to specific protocols. Each component type has an associated protocol:
 * - NextButton: NextButtonProtocol
 * - BackButton: BackButtonProtocol
 * - TextField: TextFieldProtocol
 * - DropdownButton: DropdownButtonProtocol
 * - PositionMap: PositionMapProtocol
 * - Loading: LoadingProtocol
 *
 * For each protocol, the component must implement the methods listed in the protocol.
 * 
 * propaties setter/getter
 * @method set page - Sets the current page and manages page visibility.
 * @method get page - Gets the current page.
 * @method get values - Gets the values of the components as an instance of the data model.
 * @method set errors - Sets the errors and logs the change.
 * @method get errors - Gets the errors.
 * 
 * event handlers
 * @method viewDidLoad - Called when the view is loaded.
 * @method pageChanged - Called when the page is changed.
 * @method nextButtonTapped - Called when the 'Next' button is tapped.
 * @method backButtonTapped - Called when the 'Back' button is tapped, must be overridden in the subclass.
 * @method textFieldInputValueChanged - Called when a text field input value is changed.
 * @method textFieldOnBlur - Called when a text field loses focus.
 * @method dropdownButtonSelected - Called when a dropdown button is selected.
 * @method positionMapPointerCoordinateUpdated - Called when the pointer coordinate is updated on a position map.
 * @method valueChanged - Called when a component value is changed, should be overridden in the subclass.
 * @method unfocused - Called when a component loses focus, should be overridden in the subclass.
 * 
 * methods
 * @method setAlertMessage - Sets an alert message to a specified component.
 * @method validateComponent - Validates a specific component.
 * @method validatePage - Validates all components in a specific page.
 * @method post - Sends a POST request to a specified URL with the current values.
 * @method startLoading - Starts loading.
 * @method stopLoading - Stops loading.
 * @method goTo - Navigates to a specified URL.
 * @method componentByFieldName - Returns a component by a field name.
 * @method componentById - Returns a component by an id.
 *
 * setup or internal functions
 * @method _checkProtocolAdherence - Verifies if the InputPageViewController adheres to required protocols.
 * @method _checkProtocolAdherenceForClass - Checks the adherence to a specific protocol class.
 * @method _setElements - Sets the elements of the input pages and their components.
 * @method _setPageComponent - Sets a component in a specific page.
 * @method _setEventHandlers - Sets the event handlers for the page load and hash change events.
 * @method _setvalueforkey - Sets the value of a specific key (component field name).
 * @method _setValuesForKeys - Sets the values for multiple keys (component field names).
 * @method _updatePageNumberInBrowswerURL - Updates the page number in the URL.
 */
class InputPageViewController {
    _pageIndex = null;  // Current page index
    _values = {};  // Object for storing form values
    
    _pages = [];
    _components = [];  // Array for storing all form components
    _pageComponents = [];  // [[comp 0 in page 0, comp 1 in page 0, ..], [..],..]
    
    _locale = null;  // Locale text dictionary 
    _lang = null;  // Language of the user

    constructor(
            parent_id,
            id,
            pages,
            locale,
            lang,
            dataModelClass,
            url,
            loading,
            alertMesage = new AlertMessage(id, 'AlertMessage'),
            defaultPageIndex = 0,
            isEnterButtonToNext = true
            ) {
        this.__parent_id__ = parent_id;
        this.__id__ = id;
        this.__submit_url__ = url;
        this._locale = locale;
        this._lang = lang;

        this.pages = pages;
        this.loading = loading;
        this.alertMessage = alertMesage;
        this.isEnterButtonToNext = isEnterButtonToNext;

        // Potentially check protocol adherence here
        this._checkProtocolAdherence();

        // setup page components
        this._setElements(pages);

        // set events
        this._setEventHandlers();

        // data model
        this.__data_model__ = dataModelClass;
        //this._resetValuesInCookie(); // DEBUG:

        // defalut values are set to each component
        console.table(this._values);
        console.log(`data model for ${this.__id__} initialized`);

        // locale
        console.log(locale);
        console.log(lang);
        if (this._locale == null) {
            console.warn(`no locale json data found.`);
        } else {
            console.log('locale json data found');
        }
        if (this._lang == null) {
            console.warn(`no language information is given.`);
        } else {
            console.log(`initial language is set as ${lang}`);
        }

        // loading
        this.loading = loading

        // start page index
        this.pageIndex = defaultPageIndex;
    }

    /**
     * This method checks the adherence of the InputPageViewController to the defined protocols.
     * The protocols checked are: NextButtonProtocol, BackButtonProtocol, TextFieldProtocol, and DropdownButtonProtocol.
     * If a required method from a protocol is not implemented, it will throw an error.
     */
    _checkProtocolAdherence() {
        this._checkProtocolAdherenceForClass(NextButtonProtocol);
        this._checkProtocolAdherenceForClass(BackButtonProtocol);
        this._checkProtocolAdherenceForClass(TextFieldProtocol);
        this._checkProtocolAdherenceForClass(DropdownButtonProtocol);
        this._checkProtocolAdherenceForClass(PositionMapProtocol);
        this._checkProtocolAdherenceForClass(FileUploadViewProtocol);
        this._checkProtocolAdherenceForClass(LoadingProtocol);
    }

    /**
     * This method checks the adherence of the InputPageViewController to a given protocol class.
     * It creates an instance of the protocol class, iterates over its methods, and checks that each is implemented in the InputPageViewController.
     * If a required method is not implemented, it will throw an error.
     * 
     * @param {Object} protocolClass - The protocol class to check adherence to.
     * @throws {Error} If a required method from the protocol class is not implemented.
     */
    _checkProtocolAdherenceForClass(protocolClass) {
        Object.getOwnPropertyNames(protocolClass.prototype).forEach(methodName => {
            if (methodName !== "constructor" && typeof this[methodName] !== "function") {
                throw new Error(`InputPageViewController must implement ${methodName} method of ${protocolClass.name}`);
            }
        });
    }
    

    /**
     * pageIndex setter / getter
     * 
     * Display only the pageIndex in current state.
     */
    set pageIndex(pageIndex) {
        const previousPageIndex = this._pageIndex;
        debuglog(`pageIndex changed ${previousPageIndex} -> ${pageIndex}`)
        this._pageIndex = pageIndex;
        // display only the page in current state.
        let $pages = this.$inputPageView.querySelectorAll('.inputPageViewPage')
        $pages.forEach(($page, i) => {
            if (parseInt($page.dataset.pageIndex) == this._pageIndex) {
                $page.classList.add('show');
                $page.style.display = "flex";
                $page.style.flexDirection = "column";
            } else {
                $page.classList.remove('show');
                $page.style.display = "none";
            }
        })
        if (!(isNaN(this._pageIndex))) {
            // call interface
            this.pageIndexChanged(this._pageIndex);
            // update browser's url
            this._updatePageNumberInBrowswerURL(this._pageIndex);
        }
    }

    get pageIndex() {return this._pageIndex}

    /**
     * values  getter
     */
    get values() {
        let _values = {};
        this._components.forEach((component, i) => {
            if (component.__field_name__) {
                _values[component.__field_name__] = component.value;
            }
        });
        return new this.__data_model__(_values);
    }

    /**
     * errors setter / getter
     */
    set errors(errors) {
        const previous = this._errors;
        this._errors = errors;
        console.log(`errors changed`);
        console.table(this._errors);
    }

    get errors() {return this._errors}


    /**
     * DOM nodes as variables.
     */
    _setElements(pages) {
        if (pages.length == 0) {
            console.error(`${this.__id__} requires a list of pages with components.`)
        }

        this.$parentView = document.getElementById(this.__parent_id__);
        if (this.$parentView == null) {
            console.error(
                `The parent element id=${this.__parent_id__} is necessary in HTML.`);
        }

        // create view
        let $inputPageView = document.createElement('div');
        $inputPageView.id = self.__id__;
        $inputPageView.classList.add()
        this.$inputPageView = $inputPageView;
        this.$parentView.prepend($inputPageView)

        // create container
        let $container = document.createElement('div');
        $container.id = 'inputPageViewContainer';
        $container.classList.add($container.id);
        this.$inputPageView.appendChild($container);

        // loading
        this.loading.addToParent($container);

        // create pages
        console.log(`${pages.length} pages detected.`)
        let $pagesContainer = document.createElement('div');
        $pagesContainer.classList.add('inputPageViewPages');

        pages.forEach((page, i) => {
            console.log(`${this.__id__} page ${i} has ${page.components.length} components.`);
    
            // create page DOM element
            let $page = document.createElement('div');
            $page.id = page.__id__;
            $page.classList.add('inputPageViewPage');
            $page.dataset.pageIndex = i;
    
            // set components
            page.components.forEach((component, j) => {
                this._setPageComponent(component, $page, i, j);
            });
    
            $pagesContainer.appendChild($page);
        });
        $container.appendChild($pagesContainer);

        // alert message
        this.alertMessage.addToParent($container);
    }

    /**
     * Set page component.
     * 
     * @param {object} component 
     * @param {DOM} $parent 
     * @param {number} pageIndex 
     * @param {number} componentIndex 
     */
    _setPageComponent(component, $parent, pageIndex, componentIndex) {
        if (component.constructor.name == "Wrapper") {
            let $wrapper = document.createElement('div');
            $wrapper.id = component.__id__;
            $wrapper.classList.add('wrapper');
            component.components.forEach((componentInWrapper, k) => {
                this._setPageComponent(componentInWrapper, $wrapper, pageIndex, k);
                componentInWrapper.addToParent($wrapper);
            });
        } else {
            let _id = component.__id__;
            if (_id == null) {
                console.error(`page ${pageIndex} component ${componentIndex}: no __id__ is set in the instance.`);
            }
    
            // Set the viewController for the component
            component.setViewController(this);
            component.addToParent($parent);
    
            // keep components in the ViewController instance
            this._components.push(component);
            // keep components in matrix with rows as pages
            if (componentIndex == 0 && this._pageComponents[pageIndex] == null) {
                this._pageComponents[pageIndex] = [];
            }
            this._pageComponents[pageIndex].push(component);
        }
    }

    /**
     * Set event handlers.
     */
    _setEventHandlers() {
        const _this = this;
        window.addEventListener('load', (event) => {
            console.log('** the whole page has been loaded. **');
            _this.viewDidLoad();
        })
        window.addEventListener('hashchange', (event) => {
            console.log('hashchange event detected');
            console.log(`url changed. -> ${Browser.getRelativePath()}`)
            const page = Browswer.getValueFromHash('page', 'int');
            _this.pageIndex = page;
        }, false);
        if(this.isEnterButtonToNext) {
            window.addEventListener('keydown', (event) => {
                if (event.key === 'Enter') {
                    // "Enter" was pressed, call nextButtonTapped()
                    this._nextButtonAction();
                    event.preventDefault(); // to prevent form submission or other default behavior
                }
            });
        }
    }

    /**
     * Update url ?page= in browser's addressbar.
     * 
     * @param {number} page new page number
     */
    _updatePageNumberInBrowswerURL(page) {
        //browser.updateValueInSearchParams('page', String(page), true);
        if (isNaN(page)) {
            console.error(`invalid page number ${page} of type ${typeof page}`);
            return
        }
        Browser.updateValueInHash('page', String(page), true);
    }

    /**
     * [WILL DEPRECATE]
     * Get values from Cookie.
     * 
     * @returns {dict} field values {field_name1: value1, ..}
     */
    _getValuesFromCookies() {
        let valuesInCookie = {};
        this._components.forEach((component) => {
            if (component instanceof TextField || component instanceof DropdownButton) {
                const name = `${component.__field_name__}`;
                const value = Cookies.get(name);
                if (value != null) {
                    valuesInCookie[component.__field_name__] = Cookies.get(name);
                }
            }
            if (component instanceof PositionMap) {
                const name_lat = `${component.__field_name_lat__}`;
                const name_lng = `${component.__field_name_lng__}`;
                const value_lat = Cookies.get(name_lat);
                const value_lng = Cookies.get(name_lng);
                if (value_lat != null) {
                    valuesInCookie[component.__field_name_lat__] = Cookies.get(name_lat);
                }
                if (value_lng != null) {
                    valuesInCookie[component.__field_name_lng__] = Cookies.get(name_lng);
                }
            }
        })
        console.log('-------- cookie strage ------');
        console.table(valuesInCookie);
        return valuesInCookie
    }

    /**
     * Initialize Cookie storage.
     * *For debug purpose.
     */
    _resetValuesInCookie() {
        this._components.forEach((component) => {
            if (Utils.isInheritedFrom(component, FormComponentBase)) {
                component._removeValueInCookies();
                console.log(`${component.__field_name__} removed from cookie.`);
            }
        });
        console.log(`Reset all cookies for ${this.__id__}.`);
    }

    /**
     * @interface
     * 
     * Called when the whole page has been loaded.
     * 
     */
    viewDidLoad() {
        // NOTE: override this function
    }

    /**
     * @interface
     * 
     * Called when pageIndex changed.
     * @param {Int} pageIndex
     */
    pageIndexChanged(pageIndex) {
        // NOTE: override this function
    }

    /**
     * Method that is called when the next button is tapped.
     * If it's not the last page, this function validates the current page and moves to the next one if validation passes.
     * If it's the last page, this function submits the form values.
     * This method can be overridden by subclasses to provide specific functionality.
     *
     * @param {NextButton} nextButton - The next button instance that was tapped.
     */
    nextButtonTapped(nextButton) {
        console.debug(`Button ${nextButton.__id__} tapped.`);
        console.log(this.values);
        console.log(this._getValuesFromCookies());
        
        this._nextButtonAction();
    }

    _nextButtonAction() {
        // If not the last page, navigate to the next page. If it is the last page, submit the data.
        const isLastPage = this.pageIndex == this.pages.length - 1;
        if (isLastPage) {
            this._submitData(this.__submit_url__);
        } else {
            this._navigateToNextPage();
        }
    }

    /**
     * Validates the current page and if validation passes, navigates to the next page.
     * Manages loading animation during these processes.
     */
    _navigateToNextPage() {
        this.startLoading();

        // Validate current page
        const errors = this._validatePage(this.pageIndex);
        if (errors.length > 0) {
            this.stopLoading();
            return; // Return early if there are validation errors
        }

        // If validation passes, move to the next page
        this.pageIndex += 1;
        this.stopLoading();
    }

    /**
     * Validates all pages and if validation passes, submits the form.
     * Manages loading animation during these processes.
     */
    _submitData(url) {
        this.startLoading();

        // Validate all pages and stop loading if there's an error.
        if (this.pages.some((page, i) => this._validatePage(i).length > 0)) {
            this.stopLoading();
            return; // Return early if there are validation errors
        }

        console.log(`[Field values] ${JSON.stringify(this.values)}`);
        this._submit(url, this.values);
        this.stopLoading();
    }

    /**
     * Handles successful form submission.
     * 
     * @param {Object} res The response from the server.
     * 
     * Example Success Response:
     * {
     *   'saved_data': user.response_json(),
     *   'user_id': user_id,
     *   'success': {
     *       'code': 201,
     *       'message': 'new user created.'
     *   }
     * }
     * 
     * Example Error Response:
     * {
     *   'saved_data': user.response_json(),
     *   'error': {
     *     'key': 'user_id',
     *     'code': ErrorCode.BAD_REQUEST.value,
     *     'reason': 'BAD_REQUEST',
     *     'message': 'The user_id is invalid.'
     *   }
     * }
     */
    _onSubmitSuccess(res) {
        // Success object returned.
        if (!('error' in res)) {
            console.log(`[success] ${res.success.code} ${res.success.message}`);
            this.alertMessage.hide()

            setTimeout(() => { this.stopLoading(); }, 1000);
            // Reset cookie storage
            //this._resetValuesInCookie();

        // Error object returned.
        } else {
            console.log(`[error] ${res.error.code} ${res.error.reason}`);

            // Handle by error types
            if ('errors' in res) {
                // Validation error
                console.log(`${res.errors.length} errors found.`);
                this.alertMessage.hide();
                res.errors.forEach((error) => {
                    console.warn(`[key] ${error.field_name} [message] ${error.message}`);

                    let component = this.componentByFieldName(error.field_name)
                    component.alert(true, error.message);
                })
            } else {
                // Request error
                this.alertMessage.show(res.error.message)
            }
        }
    }

    /**
     * Handles errors during form submission.
     * 
     * @param {Object} error The error object from the fetch promise.
     * 
     * Example Error Object:
     * {
     *   'type': 'fetch_error',
     *   'message': 'Network request failed'
     * }
     */
    _onSubmitError(error) {
        console.warn('↑↑↑↑ API request error');
        setTimeout(() => { this.stopLoading(); }, 1000);
    }


    _submit(url, values) {
        // Send data
        Http.post(
            url, 
            values, 
            this._onSubmitSuccess.bind(this),
            this._onSubmitError.bind(this)
        );
    }

    /**
     * Called when the back button is tapped. Classes extending InputPageViewController
     * and implementing BackButtonProtocol should override this method to provide
     * their own functionality when the back button is clicked.
     *
     * @abstract
     * @param {BackButton} backButton - The back button that was tapped.
     * @throws {Error} Will throw an error if the method is not overridden in a child class.
     */
    backButtonTapped(backButton) {
        debuglog(`button ${backButton.__id__} tapped.`);
        if (this.pageIndex > 0) {
            this.pageIndex = this.pageIndex - 1;
        }
    }

    /**
     * Called when a TextField input changes.
     * This method needs to be overridden by subclasses.
     * @param {TextField} textField - The TextField instance where the input changed.
     * @param {string} value - The new input value.
     */
    textFieldInputValueChanged(textField, value) {
        if(typeof this.valueChanged !== 'function'){
            throw new Error(`Instance ${this.__id__} must implement the method valueChanged in subclass!`);
        }
        console.log(`textField ${textField.__id__} input with value ${value}.`);
        this.valueChanged(textField, value);
        //this._setValueForKey(textField.__field_name__, value)
        //if(typeof this._setValueForKey !== 'function'){
        //    throw new Error(`Instance ${this.__id__} must implement the method _setValueForKey in subclass!`);
        //}
    }

    /**
     * Called when a TextField loses focus (unfocus).
     * This method needs to be overridden by subclasses.
     * @param {TextField} textField - The TextField instance that lost focus.
     * @param {string} value - The current value of the TextField.
     */
    textFieldOnBlur(textField, value) {
        if(typeof this.unfocused !== 'function'){
            throw new Error(`Instance ${this.__id__} must implement the method unfocused in subclass!`);
        }
        console.log(`textField ${textField.__id__} onblur with value ${value}.`);
        this.unfocused(textField, value);
    }

    /**
     * @interface
     * 
     * Called when a DropdownButton is selected.
     * 
     * @param {DropdownButton} dropdownButton
     * @param {string} value
     */
    dropdownButtonSelected(dropdownButton, value) {
        console.log(`dropdownButton ${dropdownButton.__id__} selected with value ${value}.`);
        this.unfocused(dropdownButton, value);
        this.valueChanged(dropdownButton, value);
        // NOTE: override this function
        //this._setValueForKey(dropdownButton.__field_name__, value)
    }

    /**
     * @interface
     * 
     * Called when a PositionMap.pointerCoordinate is updated.
     * 
     * @param {Coordinate} newCoordinate 
     */
    positionMapPointerCoordinateUpdated(positionMap, newCoordinate) {
        console.log(`positionMap ${positionMap.__id__}.pointerCoordinate updated with value ${newCoordinate.lat} ${newCoordinate.lng}`);
        const keyLat = `${positionMap.__field_name_lat__}`;
        const keyLng = `${positionMap.__field_name_lng__}`;
        this.valueChanged(positionMap, newCoordinate);
        //this._setValuesForKeys(
        //    {
        //        [keyLat]: newCoordinate.lat,
        //        [keyLng]: newCoordinate.lng
        //    }
        //)
        // NOTE: override this function
    }

    /**
     * @interface
     * FileUploadView protocol
     */
    fileUploadViewStateChange(fileUploadView, state) {
    }
    fileUploadViewFileUploaded(fileUploadView, file) {
    }
    fileUploadViewFocusChange(fileUploadView, focus) {
    }
    fileUploadViewFileRemoved(fileUploadView, cell) {
    }

    /**
     * @interface
     * 
     * Called when a TextField is input changed or,
     * Called when a DropdownButton is selected.
     * 
     * @param {TextField/DropdownButton} component
     * @param {string} value
     */
    valueChanged(component, value) {
        // NOTE: override this function
    }

    /**
     * @interface
     * 
     * Called when a TextField is blur(unfocus) or,
     * Called when a DropdownButton is selected.
     * 
     * @param {TextField/DropdownButton} component
     * @param {string} value
     */
    unfocused(component, value) {
        // NOTE: override this function
    }

    /**
     * @interface
     * 
     * Run validation for a single component.
     * 
     * @param {ViewComponentBase} component - The component to validate.
     * @return {string|null} - The error message if validation fails, or null if it passes.
     */
    _validateComponent(component) {
        debuglog(`Validating component: ${component.__id__}`)
        return component.validate()
    }

    /**
     * Run validation for a page.
     * 
     * @description _validateComponent(component, value) must be implemented.
     * 
     * @param {number} pageIndex
     * @returns {Array} a 2-dim list of all errors found in the page.
     * [[component, 'error message'], ..}
     */
    _validatePage(pageIndex) {
        let errors = [];
        this._pageComponents[pageIndex].forEach((component, j) => {
            if (component instanceof TextField || component instanceof DropdownButton) {
                const errorMessage = this._validateComponent(component);
                if (errorMessage != null) {
                    errors.push([component, errorMessage]);
                }
            }
        });
        console.log(`Page ${pageIndex} validated: ${errors.length} errors found.`)
        return errors
    }

    /**
     * HTTP POST to submit data.
     * 
     * @param {string} url
     * @param {function} onsuccess
     * @param {function} onfailed
     */
    post(url, onsuccess, onfailed) {
        fetch(
            url,
            {
                method: 'POST',
                headers: {
                    //'Content-Type': 'application/x-www-form-urlencoded',
                    'Content-Type': 'application/json',
            },
            // DataModel object as this._values
            body: this._values.json()
        })
        .then(response => response.json())
        .then(data => {
            console.info(`${url} response received:`, data);
            onsuccess(data);
        })
        .catch((error) => {
            console.info(`${url} request failed:`, error);
            onfailed(error);
        })
    }

    /**
     * @method
     * Start loading. Implement this in subclass.
     */
    startLoading() {
        this.loading.startLoading();
    }

    /**
     * @method
     * Stop loading. Implement this in subclass.
     */
    stopLoading() {
        this.loading.stopLoading();
    }

    /**
     * @interface
     * 
     * @param {string} newUrl 
     */
    goTo(newUrl) {
        document.location.href = newUrl;
    }

    /**
     * Returns an input component by fieldName.
     * 
     * @param {string} fieldName 
     */
    componentByFieldName(fieldName) {
        for (let component of this._components) {
            if (component.__field_name__ === fieldName) {
                debuglog(`componentByFieldName found component by ${fieldName}`);
                return component;
            }
        }
        console.warn(`input component ${fieldName} not found in component list.`);
        return null;  // Return null when the component is not found
    }

    /**
     * Returns a component by id.
     * 
     * @param {string} __id__
     */
    componentById(__id__) {
        for (let component of this._components) {
            if (component.__id__ === __id__) {
                debuglog(`componentByFieldName found component by ${__id__}`);
                return component;
            }
        }
        console.warn(`component ${__id__} not found in component list.`);
        return null;  // Return null when the component is not found
    }

}